echo "Setting up environment..."
config_path="$HOME/.bashrc"
workspace_repo_dir="/workspace/learn-spring"
echo "Finished setting up environment:"
echo "  config_path: ${config_path}"
echo "  workspace_repo_dir: ${workspace_repo_dir}"
echo "-------------------------------------------------------------------"
echo ""
